//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebformsPOCDemo
{


    public partial class manage_BankAccount
    {

        /// <summary>
        /// formControl_Wrapper_Edit_Bank_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Bank_Name;

        /// <summary>
        /// textbox_Bank_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Bank_Name;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Bank_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Bank_Name;

        /// <summary>
        /// label_Bank_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Bank_Name;

        /// <summary>
        /// formControl_Wrapper_Edit_Bank_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Bank_Number;

        /// <summary>
        /// textbox_Bank_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Bank_Number;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Bank_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Bank_Number;

        /// <summary>
        /// label_Bank_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Bank_Number;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Name;

        /// <summary>
        /// textbox_Branch_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_Name;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Name;

        /// <summary>
        /// label_Branch_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Name;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Number;

        /// <summary>
        /// textbox_Branch_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_Number;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Number;

        /// <summary>
        /// label_Branch_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Number;

        /// <summary>
        /// formControl_Wrapper_Edit_Account_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Account_Number;

        /// <summary>
        /// textbox_Account_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Account_Number;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Account_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Account_Number;

        /// <summary>
        /// label_Account_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Account_Number;

        /// <summary>
        /// formControl_Wrapper_Edit_Account_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Account_Name;

        /// <summary>
        /// textbox_Account_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Account_Name;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Account_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Account_Name;

        /// <summary>
        /// label_Account_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Account_Name;

        /// <summary>
        /// validator_Account_Name_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Account_Name_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_IBAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_IBAN;

        /// <summary>
        /// textbox_IBAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_IBAN;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_IBAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_IBAN;

        /// <summary>
        /// label_IBAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_IBAN;

        /// <summary>
        /// formControl_Wrapper_Edit_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Currency;

        /// <summary>
        /// dropdown_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Currency;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Currency;

        /// <summary>
        /// label_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Currency;

        /// <summary>
        /// formControl_Wrapper_Edit_Opened_Account_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Opened_Account_DateTime;

        /// <summary>
        /// textbox_Opened_Account_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Opened_Account_DateTime;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Opened_Account_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Opened_Account_DateTime;

        /// <summary>
        /// label_Opened_Account_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Opened_Account_DateTime;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Country;

        /// <summary>
        /// dropdown_Branch_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Branch_Country;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Country;

        /// <summary>
        /// label_Branch_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Country;

        /// <summary>
        /// up_StateUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_StateUpdatePanel;

        /// <summary>
        /// p_State_Wrapper_Panel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel p_State_Wrapper_Panel;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_State;

        /// <summary>
        /// dropdown_Branch_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Branch_State;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_State;

        /// <summary>
        /// label_Branch_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_State;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_City;

        /// <summary>
        /// textbox_Branch_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_City;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_City;

        /// <summary>
        /// label_Branch_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_City;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Address;

        /// <summary>
        /// textbox_Branch_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_Address;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Address;

        /// <summary>
        /// label_Branch_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Address;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Zipcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Zipcode;

        /// <summary>
        /// textbox_Branch_Zipcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_Zipcode;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Zipcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Zipcode;

        /// <summary>
        /// label_Branch_Zipcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Zipcode;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Phone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Phone;

        /// <summary>
        /// textbox_Branch_Phone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_Phone;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Phone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Phone;

        /// <summary>
        /// label_Branch_Phone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Phone;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Main_Email_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Main_Email_Address;

        /// <summary>
        /// textbox_Branch_Main_Email_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_Main_Email_Address;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Main_Email_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Main_Email_Address;

        /// <summary>
        /// label_Branch_Main_Email_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Main_Email_Address;

        /// <summary>
        /// formControl_Wrapper_Edit_Branch_Main_Contact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Branch_Main_Contact;

        /// <summary>
        /// textbox_Branch_Main_Contact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Branch_Main_Contact;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Branch_Main_Contact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Branch_Main_Contact;

        /// <summary>
        /// label_Branch_Main_Contact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Branch_Main_Contact;

        /// <summary>
        /// formControl_Wrapper_Edit_Main_Contact_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Main_Contact_Phone_Number;

        /// <summary>
        /// textbox_Main_Contact_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Main_Contact_Phone_Number;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Main_Contact_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Main_Contact_Phone_Number;

        /// <summary>
        /// label_Main_Contact_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Main_Contact_Phone_Number;

        /// <summary>
        /// formControl_Wrapper_Edit_Account_Active_From_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Account_Active_From_Date;

        /// <summary>
        /// textbox_Account_Active_From_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Account_Active_From_Date;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Account_Active_From_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Account_Active_From_Date;

        /// <summary>
        /// label_Account_Active_From_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Account_Active_From_Date;

        /// <summary>
        /// formControl_Wrapper_Edit_Account_Active_To_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Account_Active_To_Date;

        /// <summary>
        /// textbox_Account_Active_To_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Account_Active_To_Date;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Account_Active_To_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Account_Active_To_Date;

        /// <summary>
        /// label_Account_Active_To_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Account_Active_To_Date;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// label_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Followers_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users;

        /// <summary>
        /// label_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Active;

        /// <summary>
        /// checkbox_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Active;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Active;

        /// <summary>
        /// label_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Active;

        /// <summary>
        /// formControl_Wrapper_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Created_By_User;

        /// <summary>
        /// label_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Created_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Creation_DateTime_UTC;

        /// <summary>
        /// label_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Creation_DateTime_UTC;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_By_User;

        /// <summary>
        /// label_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// label_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// button_Edit_BankAccount_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Edit_BankAccount_Details;

        /// <summary>
        /// button_Update_BankAccount_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Update_BankAccount_Details;

        /// <summary>
        /// button_CancelEdit_BankAccount_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_CancelEdit_BankAccount_Details;

        /// <summary>
        /// lbl_Insert_Process_Error_Result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_Insert_Process_Error_Result;
    }
}
