//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebformsPOCDemo
{


    public partial class manage_CreditCardStatementTransaction
    {

        /// <summary>
        /// tab_Button_General_Info control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink tab_Button_General_Info;

        /// <summary>
        /// tab_Button_Documents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink tab_Button_Documents;

        /// <summary>
        /// General_Info control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel General_Info;

        /// <summary>
        /// up_Statement_Transaction_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_Statement_Transaction_Details;

        /// <summary>
        /// formControl_Wrapper_Edit_Transaction_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Transaction_Date;

        /// <summary>
        /// textbox_Transaction_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Transaction_Date;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Transaction_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Transaction_Date;

        /// <summary>
        /// label_Transaction_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Transaction_Date;

        /// <summary>
        /// formControl_Wrapper_Edit_Business_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Business_Name;

        /// <summary>
        /// textbox_Business_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Business_Name;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Business_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Business_Name;

        /// <summary>
        /// label_Business_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Business_Name;

        /// <summary>
        /// formControl_Wrapper_Edit_Transaction_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Transaction_Amount;

        /// <summary>
        /// textbox_Transaction_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Transaction_Amount;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Transaction_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Transaction_Amount;

        /// <summary>
        /// label_Transaction_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Transaction_Amount;

        /// <summary>
        /// formControl_Wrapper_Edit_Payment_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Payment_Currency;

        /// <summary>
        /// dropdown_Payment_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Payment_Currency;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Payment_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Payment_Currency;

        /// <summary>
        /// label_Payment_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Payment_Currency;

        /// <summary>
        /// formControl_Wrapper_Edit_Actual_Payment_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Actual_Payment_Amount;

        /// <summary>
        /// textbox_Actual_Payment_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Actual_Payment_Amount;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Actual_Payment_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Actual_Payment_Amount;

        /// <summary>
        /// label_Actual_Payment_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Actual_Payment_Amount;

        /// <summary>
        /// formControl_Wrapper_Edit_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Description;

        /// <summary>
        /// textbox_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Description;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Description;

        /// <summary>
        /// label_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Description;

        /// <summary>
        /// formControl_Wrapper_Edit_Has_Been_Actually_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Has_Been_Actually_Charged_In_Statement;

        /// <summary>
        /// checkbox_Has_Been_Actually_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Has_Been_Actually_Charged_In_Statement;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Has_Been_Actually_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Has_Been_Actually_Charged_In_Statement;

        /// <summary>
        /// label_Has_Been_Actually_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Has_Been_Actually_Charged_In_Statement;

        /// <summary>
        /// formControl_Wrapper_Edit_Total_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Total_Charged_In_Statement;

        /// <summary>
        /// textbox_Total_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Total_Charged_In_Statement;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Total_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Total_Charged_In_Statement;

        /// <summary>
        /// label_Total_Charged_In_Statement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Total_Charged_In_Statement;

        /// <summary>
        /// formControl_Wrapper_Edit_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_User_Description;

        /// <summary>
        /// textbox_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_User_Description;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_User_Description;

        /// <summary>
        /// label_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_User_Description;

        /// <summary>
        /// formControl_Wrapper_Edit_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_User_Comments;

        /// <summary>
        /// textbox_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_User_Comments;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_User_Comments;

        /// <summary>
        /// label_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_User_Comments;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// label_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Followers_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users;

        /// <summary>
        /// label_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Created_By_User;

        /// <summary>
        /// label_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Created_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Creation_DateTime_UTC;

        /// <summary>
        /// label_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Creation_DateTime_UTC;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_By_User;

        /// <summary>
        /// label_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// label_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// button_Edit_Credit_Card_Statement_Transaction_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Edit_Credit_Card_Statement_Transaction_Details;

        /// <summary>
        /// button_Update_Credit_Card_Statement_Transaction_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Update_Credit_Card_Statement_Transaction_Details;

        /// <summary>
        /// button_CancelEdit_Credit_Card_Statement_Transaction_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_CancelEdit_Credit_Card_Statement_Transaction_Details;

        /// <summary>
        /// lbl_Insert_Process_Error_Result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_Insert_Process_Error_Result;

        /// <summary>
        /// Documents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Documents;

        /// <summary>
        /// up_Transaction_Connected_Documents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_Transaction_Connected_Documents;

        /// <summary>
        /// panelConnected_Documentation_Title control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panelConnected_Documentation_Title;

        /// <summary>
        /// grid_Connected_Documents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid grid_Connected_Documents;

        /// <summary>
        /// panel_Connected_Documentation_No_Result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Connected_Documentation_No_Result;

        /// <summary>
        /// button_Remove_Document_Connection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Remove_Document_Connection;

        /// <summary>
        /// hidden_Document_Connection_Id_To_Remove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Document_Connection_Id_To_Remove;

        /// <summary>
        /// up_Suggested_Documents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_Suggested_Documents;

        /// <summary>
        /// panel_Suggested_Documents_Title control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Suggested_Documents_Title;

        /// <summary>
        /// grid_Suggested_Documents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid grid_Suggested_Documents;

        /// <summary>
        /// panel_Suggested_Documents_No_Results control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Suggested_Documents_No_Results;

        /// <summary>
        /// button_Add_Document_Connection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Add_Document_Connection;

        /// <summary>
        /// hidden_Document_Type_Id_To_Add_As_Connection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Document_Type_Id_To_Add_As_Connection;

        /// <summary>
        /// hidden_Document_Id_To_Add_As_Connection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Document_Id_To_Add_As_Connection;

        /// <summary>
        /// text_Filter_By_From_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox text_Filter_By_From_Date;

        /// <summary>
        /// text_Filter_By_To_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox text_Filter_By_To_Date;

        /// <summary>
        /// updatePanel_States control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updatePanel_States;

        /// <summary>
        /// dropdown_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Type;

        /// <summary>
        /// label_Filter_By_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal label_Filter_By_Type;

        /// <summary>
        /// dropdown_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Country;

        /// <summary>
        /// label_Filter_By_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal label_Filter_By_Country;

        /// <summary>
        /// panel_States control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_States;

        /// <summary>
        /// dropdown_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_State;

        /// <summary>
        /// label_Filter_By_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal label_Filter_By_State;

        /// <summary>
        /// text_Filter_By_CityAddressZipCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox text_Filter_By_CityAddressZipCode;

        /// <summary>
        /// text_Filter_By_CompanyNamePeopleName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox text_Filter_By_CompanyNamePeopleName;

        /// <summary>
        /// button_Search_Documents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Search_Documents;

        /// <summary>
        /// updatePanel_Search_Result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updatePanel_Search_Result;

        /// <summary>
        /// dataGrid_Documents_List control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid dataGrid_Documents_List;

        /// <summary>
        /// panel_Please_Search control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Please_Search;

        /// <summary>
        /// panel_No_Results_Message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_No_Results_Message;

        /// <summary>
        /// hidden_Edit_Document_Connection_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Edit_Document_Connection_Id;

        /// <summary>
        /// checkbox_DocumentConnection_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_DocumentConnection_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// checkbox_DocumentConnection_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_DocumentConnection_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// checkbox_DocumentConnection_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_DocumentConnection_Is_Visible_To_Followers_Users;

        /// <summary>
        /// checkbox_DocumentConnection_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_DocumentConnection_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// button_Popup_Save_Document_Connection_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Popup_Save_Document_Connection_Details;

        /// <summary>
        /// hidden_Add_Document_Connection_Document_Record_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Add_Document_Connection_Document_Record_Id;

        /// <summary>
        /// hidden_Add_Document_Connection_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Add_Document_Connection_Type;

        /// <summary>
        /// button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button1;

        /// <summary>
        /// hidden_Delete_Document_Connection_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Delete_Document_Connection_Id;
    }
}
