//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebformsPOCDemo
{


    public partial class manage_CreditCardStatement
    {

        /// <summary>
        /// panel_Tabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Tabs;

        /// <summary>
        /// tab_Button_General_Info control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink tab_Button_General_Info;

        /// <summary>
        /// liTab_CreditCardStatement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTab_CreditCardStatement;

        /// <summary>
        /// tab_Button_Transaction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink tab_Button_Transaction;

        /// <summary>
        /// General_Info control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel General_Info;

        /// <summary>
        /// formControl_Wrapper_Edit_BankAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_BankAccount;

        /// <summary>
        /// dropdown_BankAccounts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_BankAccounts;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_BankAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_BankAccount;

        /// <summary>
        /// label_BankAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccount;

        /// <summary>
        /// validator_Select_Bank_Account control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Select_Bank_Account;

        /// <summary>
        /// formControl_Wrapper_Edit_Credit_Card control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Credit_Card;

        /// <summary>
        /// dropdown_CreditCard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_CreditCard;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_CreditCard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_CreditCard;

        /// <summary>
        /// label_CreditCard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_CreditCard;

        /// <summary>
        /// validator_Select_Credit_Card control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Select_Credit_Card;

        /// <summary>
        /// formControl_Wrapper_Edit_CCStatement_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_CCStatement_DateTime;

        /// <summary>
        /// textbox_CCStatement_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_CCStatement_DateTime;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_CCStatement_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_CCStatement_DateTime;

        /// <summary>
        /// label_CCStatement_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_CCStatement_DateTime;

        /// <summary>
        /// validator_CCStatement_DateTime_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_CCStatement_DateTime_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Currency;

        /// <summary>
        /// dropdown_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Currency;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Currency;

        /// <summary>
        /// label_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Currency;

        /// <summary>
        /// validator_Currency_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Currency_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Total_Amount;

        /// <summary>
        /// textbox_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Total_Amount;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Total_Amount;

        /// <summary>
        /// label_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Total_Amount;

        /// <summary>
        /// validator_Total_Amount_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Total_Amount_Required;

        /// <summary>
        /// p_Edit_Statement_File_Download control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel p_Edit_Statement_File_Download;

        /// <summary>
        /// panel_Image_Download_CCStatement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Image_Download_CCStatement;

        /// <summary>
        /// link_Download_CCStatement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink link_Download_CCStatement;

        /// <summary>
        /// link_Download_CCStatement2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink link_Download_CCStatement2;

        /// <summary>
        /// p_Edit_Statement_File control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel p_Edit_Statement_File;

        /// <summary>
        /// fileUpload_CCStatement_File control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fileUpload_CCStatement_File;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// label_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Followers_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users;

        /// <summary>
        /// label_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// panel_Last_Updates_Info control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Last_Updates_Info;

        /// <summary>
        /// formControl_Wrapper_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Created_By_User;

        /// <summary>
        /// label_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Created_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Creation_DateTime_UTC;

        /// <summary>
        /// label_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Creation_DateTime_UTC;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_By_User;

        /// <summary>
        /// label_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// label_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// panel_Top_Buttons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Top_Buttons;

        /// <summary>
        /// button_Edit_CreditCardStatement_Details_Top control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Edit_CreditCardStatement_Details_Top;

        /// <summary>
        /// button_Update_CreditCardStatement_Details_Top control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Update_CreditCardStatement_Details_Top;

        /// <summary>
        /// button_CancelEdit_CreditCardStatement_Details_Top control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_CancelEdit_CreditCardStatement_Details_Top;

        /// <summary>
        /// up_Credit_Card_Transactions1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_Credit_Card_Transactions1;

        /// <summary>
        /// panel_Add_New_CCStatement_Transaction_In_The_Begining control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Add_New_CCStatement_Transaction_In_The_Begining;

        /// <summary>
        /// button_Add_New_Bank_Account_Transactions_In_The_Begining control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Add_New_Bank_Account_Transactions_In_The_Begining;

        /// <summary>
        /// repeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater repeater;

        /// <summary>
        /// hidden_Pending_Changes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Pending_Changes;

        /// <summary>
        /// panel_Add_New_CCStatement_Transaction_In_The_End control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_Add_New_CCStatement_Transaction_In_The_End;

        /// <summary>
        /// button_Add_New_Bank_Account_Transactions_In_The_End control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Add_New_Bank_Account_Transactions_In_The_End;

        /// <summary>
        /// button_Edit_CreditCardStatement_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Edit_CreditCardStatement_Details;

        /// <summary>
        /// button_Update_CreditCardStatement_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Update_CreditCardStatement_Details;

        /// <summary>
        /// button_Create_CreditCardStatement_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Create_CreditCardStatement_Details;

        /// <summary>
        /// button_CancelEdit_CreditCardStatement_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_CancelEdit_CreditCardStatement_Details;

        /// <summary>
        /// hidden_New_Credit_Card_Transaction_After_Transaction_ID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_New_Credit_Card_Transaction_After_Transaction_ID;

        /// <summary>
        /// button_Add_New_Transaction_After_Transaction_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Add_New_Transaction_After_Transaction_Id;

        /// <summary>
        /// hidden_User_Id_Owner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_User_Id_Owner;

        /// <summary>
        /// lbl_Insert_Process_Error_Result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_Insert_Process_Error_Result;

        /// <summary>
        /// Transaction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Transaction;

        /// <summary>
        /// up_BankAccountTransaction_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_BankAccountTransaction_Details;

        /// <summary>
        /// panel_BankAccountTransaction_Unconnected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_BankAccountTransaction_Unconnected;

        /// <summary>
        /// dropdown_BankAccountTransaction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_BankAccountTransaction;

        /// <summary>
        /// button_Save_BankAccountTransaction_Connection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Save_BankAccountTransaction_Connection;

        /// <summary>
        /// panel_BankAccountTransaction_Info control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel_BankAccountTransaction_Info;

        /// <summary>
        /// label_BankAccountTransaction_Transaction_Account_Balance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Transaction_Account_Balance;

        /// <summary>
        /// label_BankAccountTransaction_Transaction_Actual_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Transaction_Actual_DateTime;

        /// <summary>
        /// label_BankAccountTransaction_Positive_Amount_Entered control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Positive_Amount_Entered;

        /// <summary>
        /// label_BankAccountTransaction_Negative_Amount_Paid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Negative_Amount_Paid;

        /// <summary>
        /// label_BankAccountTransaction_Transaction_Value_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Transaction_Value_DateTime;

        /// <summary>
        /// label_BankAccountTransaction_Reference_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Reference_Number;

        /// <summary>
        /// label_BankAccountTransaction_Transaction_Bank_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Transaction_Bank_Description;

        /// <summary>
        /// label_BankAccountTransaction_Transaction_Bank_Inner_Reference_Code control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Transaction_Bank_Inner_Reference_Code;

        /// <summary>
        /// label_BankAccountTransaction_Transaction_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Transaction_User_Description;

        /// <summary>
        /// label_BankAccountTransaction_Transaction_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Transaction_User_Comments;

        /// <summary>
        /// label_BankAccountTransaction_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// label_BankAccountTransaction_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Is_Visible_To_Followers_Users;

        /// <summary>
        /// label_BankAccountTransaction_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Record_Created_By_User;

        /// <summary>
        /// label_BankAccountTransaction_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Record_Creation_DateTime_UTC;

        /// <summary>
        /// label_BankAccountTransaction_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Record_Last_Updated_By_User;

        /// <summary>
        /// label_BankAccountTransaction_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_BankAccountTransaction_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// hidden_Bank_Account_Transaction_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidden_Bank_Account_Transaction_Id;

        /// <summary>
        /// link_BankAccountTransaction_ViewMore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink link_BankAccountTransaction_ViewMore;

        /// <summary>
        /// link_BankAccountTransaction_EditDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink link_BankAccountTransaction_EditDetails;

        /// <summary>
        /// button_Delete_BankAccountTransaction_Connection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Delete_BankAccountTransaction_Connection;
    }
}
