//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebformsPOCDemo
{


    public partial class manage_Expense
    {

        /// <summary>
        /// formControl_Wrapper_Edit_Expense_Invoice_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Expense_Invoice_DateTime;

        /// <summary>
        /// textbox_Expense_Invoice_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Expense_Invoice_DateTime;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Expense_Invoice_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Expense_Invoice_DateTime;

        /// <summary>
        /// label_Expense_Invoice_DateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Expense_Invoice_DateTime;

        /// <summary>
        /// validator_Expense_Invoice_DateTime_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Expense_Invoice_DateTime_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Expense_Invoice_Time_Hours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Expense_Invoice_Time_Hours;

        /// <summary>
        /// dropdown_Invoice_Time_Hours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Invoice_Time_Hours;

        /// <summary>
        /// dropdown_Invoice_Time_Minutes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Invoice_Time_Minutes;

        /// <summary>
        /// dropdown_Invoice_Time_Seconds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Invoice_Time_Seconds;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Expense_Invoice_Time control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Expense_Invoice_Time;

        /// <summary>
        /// label_Expense_Invoice_Time control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Expense_Invoice_Time;

        /// <summary>
        /// formControl_Wrapper_Edit_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Supplier;

        /// <summary>
        /// dropdown_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Supplier;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Supplier;

        /// <summary>
        /// label_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Supplier;

        /// <summary>
        /// validator_Supplier_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Supplier_Required;

        /// <summary>
        /// up_EditExpense_AutoComplete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_EditExpense_AutoComplete;

        /// <summary>
        /// formControl_Wrapper_Edit_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Currency;

        /// <summary>
        /// dropdown_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Currency;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Currency;

        /// <summary>
        /// label_Currency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Currency;

        /// <summary>
        /// validator_Currency_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Currency_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Total_Amount;

        /// <summary>
        /// textbox_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Total_Amount;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Total_Amount;

        /// <summary>
        /// label_Total_Amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Total_Amount;

        /// <summary>
        /// validator_Total_Amount_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Total_Amount_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Vat_Percentage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Vat_Percentage;

        /// <summary>
        /// textbox_Vat_Percentage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Vat_Percentage;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Vat_Percentage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Vat_Percentage;

        /// <summary>
        /// label_Vat_Percentage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Vat_Percentage;

        /// <summary>
        /// validator_Vat_Percentage_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Vat_Percentage_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Total_Without_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Total_Without_Vat;

        /// <summary>
        /// textbox_Total_Without_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Total_Without_Vat;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Total_Without_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Total_Without_Vat;

        /// <summary>
        /// label_Total_Without_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Total_Without_Vat;

        /// <summary>
        /// validator_Total_Without_Vat_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Total_Without_Vat_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Total_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Total_Vat;

        /// <summary>
        /// textbox_Total_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Total_Vat;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Total_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Total_Vat;

        /// <summary>
        /// label_Total_Vat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Total_Vat;

        /// <summary>
        /// validator_Total_Vat_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_Total_Vat_Required;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_On_User_Location_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_On_User_Location_Id;

        /// <summary>
        /// textbox_Invoiced_On_User_Location_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_On_User_Location_Id;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_On_User_Location_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_On_User_Location_Id;

        /// <summary>
        /// label_Invoiced_On_User_Location_Id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_On_User_Location_Id;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_CompanyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_CompanyName;

        /// <summary>
        /// textbox_Invoiced_Client_To_CompanyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_CompanyName;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_CompanyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_CompanyName;

        /// <summary>
        /// label_Invoiced_Client_To_CompanyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_CompanyName;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_Tax_Reference;

        /// <summary>
        /// textbox_Invoiced_Client_To_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_Tax_Reference;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_Tax_Reference;

        /// <summary>
        /// label_Invoiced_Client_To_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_Tax_Reference;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_PersonName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_PersonName;

        /// <summary>
        /// textbox_Invoiced_Client_To_PersonName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_PersonName;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_PersonName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_PersonName;

        /// <summary>
        /// label_Invoiced_Client_To_PersonName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_PersonName;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_PhoneNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_PhoneNumber;

        /// <summary>
        /// textbox_Invoiced_Client_To_PhoneNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_PhoneNumber;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_PhoneNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_PhoneNumber;

        /// <summary>
        /// label_Invoiced_Client_To_PhoneNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_PhoneNumber;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_Country;

        /// <summary>
        /// dropdown_Invoiced_Client_To_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Invoiced_Client_To_Country;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_Country;

        /// <summary>
        /// label_Invoiced_Client_To_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_Country;

        /// <summary>
        /// up_Invoice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_Invoice;

        /// <summary>
        /// p_Invoiced_Client_To_State_Wrapper_Panel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel p_Invoiced_Client_To_State_Wrapper_Panel;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_State;

        /// <summary>
        /// dropdown_Invoiced_Client_To_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Invoiced_Client_To_State;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_State;

        /// <summary>
        /// label_Invoiced_Client_To_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_State;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_City;

        /// <summary>
        /// textbox_Invoiced_Client_To_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_City;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_City;

        /// <summary>
        /// label_Invoiced_Client_To_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_City;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_Address;

        /// <summary>
        /// textbox_Invoiced_Client_To_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_Address;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_Address;

        /// <summary>
        /// label_Invoiced_Client_To_Address control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_Address;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_Zip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_Zip;

        /// <summary>
        /// textbox_Invoiced_Client_To_Zip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_Zip;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_Zip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_Zip;

        /// <summary>
        /// label_Invoiced_Client_To_Zip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_Zip;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoiced_Client_To_EmailAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoiced_Client_To_EmailAddress;

        /// <summary>
        /// textbox_Invoiced_Client_To_EmailAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoiced_Client_To_EmailAddress;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoiced_Client_To_EmailAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoiced_Client_To_EmailAddress;

        /// <summary>
        /// label_Invoiced_Client_To_EmailAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoiced_Client_To_EmailAddress;

        /// <summary>
        /// formControl_Wrapper_Edit_Expense_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Expense_Type;

        /// <summary>
        /// dropdown_Expense_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Expense_Type;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Expense_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Expense_Type;

        /// <summary>
        /// label_Expense_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Expense_Type;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Number;

        /// <summary>
        /// textbox_Invoice_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Number;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Number;

        /// <summary>
        /// label_Invoice_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Number;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Reference_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Reference_Number;

        /// <summary>
        /// textbox_Invoice_Reference_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Reference_Number;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Reference_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Reference_Number;

        /// <summary>
        /// label_Invoice_Reference_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Reference_Number;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_Company_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_Company_Details;

        /// <summary>
        /// textbox_Invoice_Supplier_Company_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_Company_Details;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_Company_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_Company_Details;

        /// <summary>
        /// label_Invoice_Supplier_Company_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_Company_Details;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_Tax_Reference;

        /// <summary>
        /// textbox_Invoice_Supplier_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_Tax_Reference;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_Tax_Reference;

        /// <summary>
        /// label_Invoice_Supplier_Tax_Reference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_Tax_Reference;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_Country;

        /// <summary>
        /// dropdown_Invoice_Supplier_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Invoice_Supplier_Country;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_Country;

        /// <summary>
        /// label_Invoice_Supplier_Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_Country;

        /// <summary>
        /// validator_dropdown_Invoice_Supplier_Country_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validator_dropdown_Invoice_Supplier_Country_Required;

        /// <summary>
        /// up_StateUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel up_StateUpdatePanel;

        /// <summary>
        /// p_Invoice_Supplier_State_Wrapper_Panel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel p_Invoice_Supplier_State_Wrapper_Panel;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_State;

        /// <summary>
        /// dropdown_Invoice_Supplier_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropdown_Invoice_Supplier_State;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_State;

        /// <summary>
        /// label_Invoice_Supplier_State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_State;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_City;

        /// <summary>
        /// textbox_Invoice_Supplier_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_City;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_City;

        /// <summary>
        /// label_Invoice_Supplier_City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_City;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_Address_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_Address_Description;

        /// <summary>
        /// textbox_Invoice_Supplier_Address_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_Address_Description;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_Address_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_Address_Description;

        /// <summary>
        /// label_Invoice_Supplier_Address_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_Address_Description;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_ZipCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_ZipCode;

        /// <summary>
        /// textbox_Invoice_Supplier_ZipCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_ZipCode;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_ZipCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_ZipCode;

        /// <summary>
        /// label_Invoice_Supplier_ZipCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_ZipCode;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_WebAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_WebAddress;

        /// <summary>
        /// textbox_Invoice_Supplier_WebAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_WebAddress;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_WebAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_WebAddress;

        /// <summary>
        /// label_Invoice_Supplier_WebAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_WebAddress;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_Phone_Number;

        /// <summary>
        /// textbox_Invoice_Supplier_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_Phone_Number;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_Phone_Number;

        /// <summary>
        /// label_Invoice_Supplier_Phone_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_Phone_Number;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Supplier_Contact_FullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Supplier_Contact_FullName;

        /// <summary>
        /// textbox_Invoice_Supplier_Contact_FullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Supplier_Contact_FullName;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Supplier_Contact_FullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Supplier_Contact_FullName;

        /// <summary>
        /// label_Invoice_Supplier_Contact_FullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Supplier_Contact_FullName;

        /// <summary>
        /// formControl_Wrapper_Edit_Invoice_Content_Long_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Invoice_Content_Long_Description;

        /// <summary>
        /// textbox_Invoice_Content_Long_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Invoice_Content_Long_Description;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Invoice_Content_Long_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Invoice_Content_Long_Description;

        /// <summary>
        /// label_Invoice_Content_Long_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Invoice_Content_Long_Description;

        /// <summary>
        /// formControl_Wrapper_Edit_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_User_Description;

        /// <summary>
        /// textbox_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_User_Description;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_User_Description;

        /// <summary>
        /// label_User_Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_User_Description;

        /// <summary>
        /// formControl_Wrapper_Edit_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_User_Comments;

        /// <summary>
        /// textbox_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_User_Comments;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_User_Comments;

        /// <summary>
        /// label_User_Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_User_Comments;

        /// <summary>
        /// formControl_Wrapper_Edit_Original_File_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Original_File_Name;

        /// <summary>
        /// textbox_Original_File_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textbox_Original_File_Name;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Original_File_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Original_File_Name;

        /// <summary>
        /// label_Original_File_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Original_File_Name;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// label_Is_Visible_To_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Anonymous_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Anonymous_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Visible_To_Followers_Users;

        /// <summary>
        /// checkbox_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Visible_To_Followers_Users;

        /// <summary>
        /// label_Is_Visible_To_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Visible_To_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// checkbox_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// label_Is_Available_For_Download_For_Followers_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Available_For_Download_For_Followers_Users;

        /// <summary>
        /// formControl_Wrapper_Edit_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Edit_Is_Active;

        /// <summary>
        /// checkbox_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkbox_Is_Active;

        /// <summary>
        /// formControl_Wrapper_ReadOnly_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_ReadOnly_Is_Active;

        /// <summary>
        /// label_Is_Active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Is_Active;

        /// <summary>
        /// formControl_Wrapper_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Created_By_User;

        /// <summary>
        /// label_Record_Created_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Created_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Creation_DateTime_UTC;

        /// <summary>
        /// label_Record_Creation_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Creation_DateTime_UTC;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_By_User;

        /// <summary>
        /// label_Record_Last_Updated_By_User control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_By_User;

        /// <summary>
        /// formControl_Wrapper_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel formControl_Wrapper_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// label_Record_Last_Updated_DateTime_UTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label label_Record_Last_Updated_DateTime_UTC;

        /// <summary>
        /// button_Edit_Expense_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Edit_Expense_Details;

        /// <summary>
        /// button_Update_Expense_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_Update_Expense_Details;

        /// <summary>
        /// button_CancelEdit_Expense_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button_CancelEdit_Expense_Details;

        /// <summary>
        /// lbl_Insert_Process_Error_Result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_Insert_Process_Error_Result;
    }
}
